"""Send preset or scripted camera commands to the simulation service."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import List

import rclpy
from aeris_msgs.msg import CameraWaypoint
from aeris_msgs.srv import SetCameraView
from builtin_interfaces.msg import Duration
from geometry_msgs.msg import Pose
from rclpy.node import Node


def rpy_to_quat(roll: float, pitch: float, yaw: float):
    cy = math.cos(yaw * 0.5)
    sy = math.sin(yaw * 0.5)
    cp = math.cos(pitch * 0.5)
    sp = math.sin(pitch * 0.5)
    cr = math.cos(roll * 0.5)
    sr = math.sin(roll * 0.5)
    return (
        sr * cp * cy - cr * sp * sy,
        cr * sp * cy + sr * cp * sy,
        cr * cp * sy - sr * sp * cy,
        cr * cp * cy + sr * sp * sy,
    )


def load_waypoints(json_path: Path) -> List[CameraWaypoint]:
    data = json.loads(json_path.read_text())
    waypoints: List[CameraWaypoint] = []
    for entry in data.get('waypoints', []):
        waypoint = CameraWaypoint()
        time_value = float(entry.get('time_from_start', 0.0))
        secs = int(math.floor(time_value))
        nanos = int((time_value - secs) * 1e9)
        waypoint.time_from_start = Duration(sec=secs, nanosec=nanos)

        pose = Pose()
        position = entry.get('position', {})
        pose.position.x = float(position.get('x', 0.0))
        pose.position.y = float(position.get('y', 0.0))
        pose.position.z = float(position.get('z', 0.0))
        orientation = entry.get('orientation_rpy', {})
        quat = rpy_to_quat(
            float(orientation.get('roll', 0.0)),
            float(orientation.get('pitch', 0.0)),
            float(orientation.get('yaw', 0.0)),
        )
        pose.orientation.x, pose.orientation.y, pose.orientation.z, pose.orientation.w = quat
        waypoint.pose = pose
        waypoint.field_of_view_deg = float(entry.get('fov_deg', 50.0))
        waypoint.focal_distance_m = float(entry.get('focal_distance_m', 40.0))
        waypoints.append(waypoint)

    if not waypoints:
        raise ValueError(f"No waypoints found in {json_path}")
    return waypoints


class CameraViewClient(Node):
    def __init__(self) -> None:
        super().__init__('camera_view_client')
        self._client = self.create_client(SetCameraView, '/simulation/set_camera_view')
        if not self._client.wait_for_service(timeout_sec=5.0):
            raise RuntimeError('Service /simulation/set_camera_view not available')

    def send(self, args) -> None:
        request = SetCameraView.Request()
        request.target_vehicle = args.target
        request.transition_duration = args.transition
        request.tracking_mode = args.track

        if args.preset:
            request.command_type = 'preset'
            request.preset_name = args.preset
        elif args.path_json:
            request.command_type = 'path'
            request.path = load_waypoints(Path(args.path_json))
        else:
            raise RuntimeError('Provide --preset or --path-json')

        future = self._client.call_async(request)
        rclpy.spin_until_future_complete(self, future, timeout_sec=10.0)
        if future.result() is None:
            raise RuntimeError('Failed to call camera view service')
        response = future.result()
        if response.accepted:
            self.get_logger().info('Camera command accepted: %s', response.message)
        else:
            raise RuntimeError(f"Camera command rejected: {response.message}")


def main() -> None:
    parser = argparse.ArgumentParser(description='Camera view service helper')
    parser.add_argument('--preset', choices=['wide', 'tracking', 'pov', 'orbit'], help='Preset to activate')
    parser.add_argument('--path-json', help='JSON file generated by camera_path_builder.py')
    parser.add_argument('--target', default='scout1', help='Target vehicle for tracking/pov/orbit presets')
    parser.add_argument('--transition', type=float, default=3.0, help='Transition duration seconds')
    parser.add_argument('--track', action='store_true', help='Keep tracking target after first transition')
    args = parser.parse_args()

    if not args.preset and not args.path_json:
        parser.error('Provide either --preset or --path-json')

    rclpy.init()
    try:
        client = CameraViewClient()
        client.send(args)
    finally:
        rclpy.shutdown()


if __name__ == '__main__':
    main()
